spring:
  mvc:
    throw-exception-if-no-handler-found: on
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security-jwt
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: jwt-pool
      auto-commit: on
      connectionTimeout: 30000
      maxLifetime: 1800000
      idle-timeout: 600000
      data-source-properties:
        serverTimezone: Asia/Shanghai
        characterEncoding: utf-8
        useUnicode: true
        useSSL: true
        allowMultiQueries: true
        autoReconnect: true
        useLegacyDatetimeCode: true
        nullCatalogMeansCurrent: true
      connection-test-query: select 1
      maximum-pool-size: 100
      minimum-idle: 20
mybatis-plus:
  global-config:
    banner: off
  mapper-locations: classpath:cn/xwplay/security/jwt/mapper/*Mapper.xml
config:
  jwt:
    issuer: xwplay
    subject: smart-public-wm
    token-header: token
    # 15天，单位：分钟
    expirationTimeInMinute: 21600